### ISSUE TITLE
Pity set at 80?

### ISSUE THREAD

**Issue by kimira** [uzair-ashraf/genshin-impact-wish-simulator#81]
Hi, I really love this wish simulator, it's my favorite of ones I've come across. I've just noticed using it that I've never had a banner go to 90 pulls. I always get a 5 star in 80 pulls maximum. This seems extremely statistically unlikely so I wondered if maybe pity is erroneously kicking in at 80 instead of 90?

**Comment by uzair-ashraf** [comment]
The pity system was completely reworked by @elebitzero , they can possibly answer your question 👍🏼

**Comment by Klamist** [comment]
There's a soft pity system for wish in Genshin, and this simulator has applied it somehow. The chance to get 5-star in 90 pulls is much smaller than getting within 80 pulls.

I don't know the exact setting in the simulator now, but for the real game, the most probable soft pity is like:
0.6% for 5 star before No.74 pull, since last time you get a 5-star.
0.6% + 6% * (n-73), n is the number that how many wishes without 5-star.
This conclusion came from [https://github.com/OneBST/GI_gacha_dataset](url), which gathered 200k wishes record from different players and analyzed.

By this rule, 80+ pity has a 8% chance to reach.
